apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-ship-it.fullname" . }}
  labels:
    {{- include "go-ship-it.labels" . | nindent 4 }}
type: Opaque
data:
  webhook-secret: {{ b64enc .Values.githubsecret | quote }}
  key.pem: {{ b64enc .Values.keypem | quote }}
  